name: Publish website
on:
  workflow_run:
    workflows: [ "Build website" ]
    types:
      - completed

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      PR_INFO_FILE: ".PR_INFO"
    steps:
      - if: github.event.workflow_run.conclusion != 'success'
        name: Abort if build failed
        run: |
          echo "build failed"
          exit 1

      - uses: actions/checkout@v3

      - name: Download build artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          workflow: build-website.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: website
          path: dist

      - if: github.event.workflow_run.event == 'pull_request'
        name: Download pr info
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: "${{ secrets.GITHUB_TOKEN }}"
          workflow: build-website.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: pr-info

      - if: github.event.workflow_run.event == 'pull_request'
        name: Apply pull request environment
        run: |
          pr_number=$(cat "$PR_INFO_FILE")
          if ! [[ "$pr_number" =~ ^[0-9]+$ ]]; then
            echo "pr number invalid"
            exit 1
          fi
          pr_branch="${{ github.event.workflow_run.head_branch }}"
          echo "PR_NUMBER=$pr_number" >> $GITHUB_ENV
          echo "PR_BRANCH=${{ github.event.workflow_run.head_branch }}" >> $GITHUB_ENV
          echo "COMMIT_SHA=${{ github.event.workflow_run.head_sha }}" >> $GITHUB_ENV
          echo "CHANNEL_ID=pr$pr_number-$pr_branch" >> $GITHUB_ENV
